INRETS and bpr2 VD functions
AequilibraE/aequilibrae pull request #273
Opened 2021-10-20 12:58 UTC by Art-Ev

Just adding INRETS and a BPR2 VD function.
Not fully tested but I think it should work almost as it is.

2021-10-21 09:56 UTC, Art-Ev commented
First styling revision, do we need to correct all E501 error (line too long) ?
Anything to check for pyx and rst files ?

2021-10-21 10:17 UTC, pedrocamargo commented on aequilibrae/paths/bpr2.pyx
> +        if link_flows[i] > capacity[i]:
This indentation here looks funny. Can you change it for the PEP8 standard of 4 spaces?

2021-10-21 10:21 UTC, pedrocamargo commented
Some documentation on INRETS, @janzill http://transportproblems.polsl.pl/pl/Archiwum/2017/zeszyt1/2017t12z1_04.pdf

2021-10-21 10:22 UTC, pedrocamargo commented on aequilibrae/paths/inrets.pyx
> +        if link_flows[i] > capacity[i]:
Same here

2021-10-21 10:25 UTC, pedrocamargo requested changes
@Art-Ev , it looks excellent, aside from the issue with indentation and the lack of testing.  You can look at this file for reference: https://github.com/AequilibraE/aequilibrae/blob/master/tests/aequilibrae/paths/test_conical.py

2021-10-21 11:21 UTC, pedrocamargo commented
I second @janzill 's comment on tests. We are actually expanding the guidelines on collaboration to make it easier, @Art-Ev !

2021-10-21 14:09 UTC, Art-Ev commented
Can somebody check my inrets values ? Calculated them with excel but cannot retrieve exactly the same values for Spiess' conical through excel than the values in test_conical (ok at 2 decimals but values differs beyond that)

2021-11-08 09:09 UTC, pedrocamargo commented
@Art-Ev , we can go ahead and merge if you change the target from Master to Develop

2021-11-08 10:22 UTC, Art-Ev commented
> @Art-Ev , we can go ahead and merge if you change the target from Master to Develop
I thought I did it 14 days ago after Janzill message... github tells me "Art-Ev wants to merge 4 commits into AequilibraE:develop from Art-Ev:INRETS-and-BPR2-DV-functions". Where can I correct this?

2021-11-10 00:22 UTC, janzill commented
> > @Art-Ev , we can go ahead and merge if you change the target from Master to Develop
> 
> I thought I did it 14 days ago after Janzill message... github tells me "Art-Ev wants to merge 4 commits into AequilibraE:develop from Art-Ev:INRETS-and-BPR2-DV-functions". Where can I correct this?

I can see the change @pedrocamargo, will need to look into @Art-Ev's question regarding inrets comparison values

2021-11-15 01:39 UTC, pedrocamargo commented
@Art-Ev , something went haywire with those indentations.

![image](https://user-images.githubusercontent.com/7377666/141709121-31e9c6c7-17bc-4b43-bac1-f86269da6714.png)

2021-11-18 06:09 UTC, pedrocamargo approved these changes

2021-11-18 06:09 UTC, merged