Upload docs to merge_request_id on AWS
AequilibraE/aequilibrae pull request #567
Opened 2024-09-03 13:16 UTC by r-akemii

**TO-DO**:

- [x]  Find the environment variable. See: https://stackoverflow.com/questions/59077079/how-to-get-pull-request-number-within-github-actions-workflow
- [ ] Re-build the workflow

2024-09-03 14:25 UTC, r-akemii commented
@pedrocamargo I didn't manage to rename "dev" with the PR number due to an error stating that the folder with the PR number in S3 doesn't exist, but I managed to do something like "dev/PR_NUMBER", e.g.: https://aequilibrae.com/python/dev/567/index.html.

Do you think it works?

2024-09-03 20:03 UTC, pedrocamargo approved these changes

2024-09-03 20:14 UTC, pedrocamargo requested changes
It did NOT WORK. The documentation is NOT there.

You probably want to rename the docs folder locally ${{github.event.number}} and upload the entire thing

2024-09-04 22:08 UTC, pedrocamargo approved these changes

2024-09-04 22:08 UTC, merged